### PR TITLE
tweak: huayrar handling improvements

### PR DESCRIPTION
**Pull request by okxeon**

### CODE REVIEW

**Comment by Stagonium** [comment]
yeah I don't think this makes much sense given the 2.4m price

**Comment by No-Yes1** [comment]
Not sure why the sudden need to tweak vehicles that don't need tweaking

**Comment by okxeon** [comment]
it was doing 220 + for me after adding a 7th gear

**Comment by Proudcat1** [comment]
The nerf must have been accidental cause that was stupid

**Comment by okxeon** [comment]
Despite the significantly lower fInitialDriveMaxFlatVel this was a buff not a nerf. Once the car hits 7th it keeps climbing in speed hitting as fast as 230.

**Pull request merged**
